### PR TITLE
Update formrunner.js, formbuilder.js

### PR DESCRIPTION
**Pull request by usernamenotused**
use a sync call so when the templates are dynamically loaded the order persistes

### CODE REVIEW

**Comment by viveleroi** [comment]
I'm not sure what the issue with order is, but forcing synchronous requests isn't an acceptable solution.

**Comment by usernamenotused** [comment]
If so the "dynamic templates loader" needs something else. The elements
displayed are in order of which templates load in, then sort order for
larger forms. Requiring the templates to load, then rendering with dust
fixes this. Thoughts?

**Comment by viveleroi** [comment]
Can you provide a detailed list of steps to reproduce the issue?

**Comment by usernamenotused** [comment]
Let me build an example. Also I have been building a validation builder
into it with parsely.js, so my example right now has much extra code.

**Pull request closed without merging**
